/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package rce;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class RaceConditionExampleTest {
    @Test void testGetCount() {
        RaceConditionExample classUnderTest = new RaceConditionExample();
        assertNotNull(classUnderTest.getCount(), "count method should work");
    }
}

